using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using ObsidianScout.Models;
using ObsidianScout.Services;
using System.Collections.ObjectModel;
using System.Linq;
using System.Threading.Tasks;

namespace ObsidianScout.ViewModels;

public partial class MainViewModel : ObservableObject
{
    private readonly IApiService _apiService;
    private readonly ISettingsService _settingsService;

    [ObservableProperty]
    private User? currentUser;

    [ObservableProperty]
    private string welcomeMessage = "Welcome to ObsidianScout";

    [ObservableProperty]
    private bool isLoading;

    // Dashboard properties (backing fields generated by source generator)
    [ObservableProperty]
    private string currentEventName = "No current event";

    [ObservableProperty]
    private int teamCount;

    [ObservableProperty]
    private int matchCount;

    public MainViewModel(IApiService apiService, ISettingsService settingsService)
    {
        _apiService = apiService;
        _settingsService = settingsService;

        // Load basic user and dashboard data
        _ = LoadUserData();
        _ = LoadDashboardData();
    }

    [RelayCommand]
    private async Task TriggerSyncAsync()
    {
        if (IsLoading) return;

        try
        {
            IsLoading = true;
            WelcomeMessage = "Triggering server sync...";

            // Build the combined season+code event code from game config
            string? eventCode = null;
            var configResp = await _apiService.GetGameConfigAsync();
            if (configResp.Success && configResp.Config != null && !string.IsNullOrEmpty(configResp.Config.CurrentEventCode))
            {
                var rawEventCode = configResp.Config.CurrentEventCode;

                if (configResp.Config.Season > 0)
                {
                    var seasonStr = configResp.Config.Season.ToString();
                    // If the event code already starts with the season, use it as-is
                    if (rawEventCode.StartsWith(seasonStr, System.StringComparison.OrdinalIgnoreCase))
                    {
                        eventCode = rawEventCode;
                    }
                    else
                    {
                        eventCode = $"{configResp.Config.Season}{rawEventCode}";
                    }
                }
                else
                {
                    eventCode = rawEventCode;
                }
            }

            var resp = await _apiService.TriggerSyncAsync(eventCode);
            if (resp.Success)
            {
                WelcomeMessage = "Server sync triggered successfully.";
            }
            else
            {
                WelcomeMessage = $"Sync failed: {resp.Error ?? "unknown"}";
            }

            // refresh dashboard after short delay
            await Task.Delay(1200);
            _ = LoadDashboardData();
        }
        catch (Exception ex)
        {
            WelcomeMessage = $"Sync error: {ex.Message}";
        }
        finally
        {
            IsLoading = false;
        }
    }

    private async Task LoadUserData()
    {
        var token = await _settingsService.GetTokenAsync();
        if (!string.IsNullOrEmpty(token))
        {
            var result = await _apiService.VerifyTokenAsync();
            if (result.Success && result.Data != null)
            {
                CurrentUser = result.Data;
                WelcomeMessage = $"Welcome, {CurrentUser.Username}!";
            }
        }
    }

    private async Task LoadDashboardData()
    {
        if (IsLoading) return;

        try
        {
            IsLoading = true;

            // Attempt to find current event from game config
            int? currentEventId = null;

            System.Diagnostics.Debug.WriteLine("=== [MainViewModel] LoadDashboardData START ===");

            var configResp = await _apiService.GetGameConfigAsync();
            System.Diagnostics.Debug.WriteLine($"[MainViewModel] GameConfig Success: {configResp.Success}");
            
            if (configResp.Success && configResp.Config != null)
            {
                System.Diagnostics.Debug.WriteLine($"[MainViewModel] GameConfig.Season: {configResp.Config.Season}");
                System.Diagnostics.Debug.WriteLine($"[MainViewModel] GameConfig.CurrentEventCode: '{configResp.Config.CurrentEventCode}'");
            }

            if (configResp.Success && configResp.Config != null && !string.IsNullOrEmpty(configResp.Config.CurrentEventCode))
            {
                var eventsResp = await _apiService.GetEventsAsync();
                System.Diagnostics.Debug.WriteLine($"[MainViewModel] Events Success: {eventsResp.Success}, Count: {eventsResp.Events?.Count ?? 0}");
                
                if (eventsResp.Success && eventsResp.Events != null)
                {
                    // Log all available events
                    System.Diagnostics.Debug.WriteLine("[MainViewModel] Available events:");
                    foreach (var e in eventsResp.Events)
                    {
                        System.Diagnostics.Debug.WriteLine($"  - ID: {e.Id}, Code: '{e.Code}', Name: '{e.Name}'");
                    }

                    // Build the event code - check if it already includes the season prefix
                    var rawEventCode = configResp.Config.CurrentEventCode;
                    string seasonCode;

                    System.Diagnostics.Debug.WriteLine($"[MainViewModel] Raw event code: '{rawEventCode}'");
                    System.Diagnostics.Debug.WriteLine($"[MainViewModel] Season: {configResp.Config.Season}");

                    if (configResp.Config.Season > 0)
                    {
                        var seasonStr = configResp.Config.Season.ToString();
                        System.Diagnostics.Debug.WriteLine($"[MainViewModel] Season string: '{seasonStr}'");
                        
                        // If the event code already starts with the season, use it as-is
                        bool alreadyHasSeason = rawEventCode.StartsWith(seasonStr, System.StringComparison.OrdinalIgnoreCase);
                        System.Diagnostics.Debug.WriteLine($"[MainViewModel] Already has season prefix: {alreadyHasSeason}");
                        
                        if (alreadyHasSeason)
                        {
                            seasonCode = rawEventCode;
                        }
                        else
                        {
                            seasonCode = $"{configResp.Config.Season}{rawEventCode}";
                        }
                    }
                    else
                    {
                        seasonCode = rawEventCode;
                    }

                    System.Diagnostics.Debug.WriteLine($"[MainViewModel] Final seasonCode to search: '{seasonCode}'");

                    // Try exact match with season+code (primary)
                    var ev = eventsResp.Events.FirstOrDefault(e => string.Equals(e.Code, seasonCode, System.StringComparison.OrdinalIgnoreCase));
                    System.Diagnostics.Debug.WriteLine($"[MainViewModel] Match on seasonCode '{seasonCode}': {(ev != null ? $"ID={ev.Id}, Code='{ev.Code}'" : "NULL")}");
                    
                    // Fallback to raw code only
                    if (ev == null)
                    {
                        ev = eventsResp.Events.FirstOrDefault(e => string.Equals(e.Code, rawEventCode, System.StringComparison.OrdinalIgnoreCase));
                        System.Diagnostics.Debug.WriteLine($"[MainViewModel] Match on rawEventCode '{rawEventCode}': {(ev != null ? $"ID={ev.Id}, Code='{ev.Code}'" : "NULL")}");
                    }
                    
                    if (ev != null)
                    {
                        currentEventId = ev.Id;
                        System.Diagnostics.Debug.WriteLine($"[MainViewModel] *** SELECTED EVENT: ID={ev.Id}, Code='{ev.Code}', Name='{ev.Name}' ***");
                        // set backing field and notify property changed
                        currentEventName = ev.DisplayName ?? ev.Code ?? "Current Event";
                        OnPropertyChanged("CurrentEventName");
                    }
                    else
                    {
                        System.Diagnostics.Debug.WriteLine($"[MainViewModel] *** NO EVENT MATCHED! ***");
                    }
                }
            }

            // If no current event found, try to pick a first event
            if (currentEventId == null)
            {
                System.Diagnostics.Debug.WriteLine("[MainViewModel] No event found from config, falling back to first event...");
                var eventsResp = await _apiService.GetEventsAsync();
                if (eventsResp.Success && eventsResp.Events != null && eventsResp.Events.Any())
                {
                    var first = eventsResp.Events.First();
                    currentEventId = first.Id;
                    currentEventName = first.DisplayName ?? first.Code ?? "Event";
                    OnPropertyChanged("CurrentEventName");
                    System.Diagnostics.Debug.WriteLine($"[MainViewModel] Fallback to first event: ID={first.Id}, Code='{first.Code}'");
                }
            }

            System.Diagnostics.Debug.WriteLine($"[MainViewModel] Final currentEventId: {currentEventId}");

            // Load team count (for current event if available)
            int countTeams = 0;
            var teamsResp = await _apiService.GetTeamsAsync(eventId: currentEventId, limit: 500);
            if (teamsResp.Success && teamsResp.Teams != null)
            {
                // Merge by team number could happen elsewhere; here just count unique numbers
                countTeams = teamsResp.Teams.Select(t => t.TeamNumber).Distinct().Count();
            }
            teamCount = countTeams;
            OnPropertyChanged("TeamCount");

            // Load match count for current event
            int countMatches = 0;
            if (currentEventId.HasValue)
            {
                var matchesResp = await _apiService.GetMatchesAsync(currentEventId.Value);
                if (matchesResp.Success && matchesResp.Matches != null)
                    countMatches = matchesResp.Matches.Count;
            }
            matchCount = countMatches;
            OnPropertyChanged("MatchCount");

            System.Diagnostics.Debug.WriteLine($"[MainViewModel] Teams: {countTeams}, Matches: {countMatches}");
            System.Diagnostics.Debug.WriteLine("=== [MainViewModel] LoadDashboardData END ===");
        }
        catch (System.Exception ex)
        {
            System.Diagnostics.Debug.WriteLine($"[MainViewModel] LoadDashboardData error: {ex.Message}");
        }
        finally
        {
            IsLoading = false;
        }
    }

    [RelayCommand]
    private async Task LogoutAsync()
    {
        await _settingsService.ClearAuthDataAsync();

        // Update AppShell authentication state
        if (Shell.Current is AppShell appShell)
        {
            appShell.UpdateAuthenticationState(false);
        }

        await Shell.Current.GoToAsync("//LoginPage");
    }

    [RelayCommand]
    private async Task NavigateToTeamsAsync()
    {
        await Shell.Current.GoToAsync("TeamsPage");
    }

    [RelayCommand]
    private async Task NavigateToEventsAsync()
    {
        await Shell.Current.GoToAsync("EventsPage");
    }

    [RelayCommand]
    private async Task NavigateToScoutingAsync()
    {
        await Shell.Current.GoToAsync("ScoutingPage");
    }

    [RelayCommand]
    private async Task NavigateToGraphsAsync()
    {
        await Shell.Current.GoToAsync("GraphsPage");
    }
}
