using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using ObsidianScout.Models;
using ObsidianScout.Services;
using System.Collections.ObjectModel;
using System.Linq;
using System.Threading.Tasks;

namespace ObsidianScout.ViewModels;

public partial class MainViewModel : ObservableObject
{
    private readonly IApiService _apiService;
    private readonly ISettingsService _settingsService;

    [ObservableProperty]
    private User? currentUser;

    [ObservableProperty]
    private string welcomeMessage = "Welcome to ObsidianScout";

    [ObservableProperty]
    private bool isLoading;

    // Dashboard properties (backing fields generated by source generator)
    [ObservableProperty]
    private string currentEventName = "No current event";

    [ObservableProperty]
    private int teamCount;

    [ObservableProperty]
    private int matchCount;

    public MainViewModel(IApiService apiService, ISettingsService settingsService)
    {
        _apiService = apiService;
        _settingsService = settingsService;

        // Load basic user and dashboard data
        _ = LoadUserData();
        _ = LoadDashboardData();
    }

    [RelayCommand]
    private async Task TriggerSyncAsync()
    {
        if (IsLoading) return;

        try
        {
            IsLoading = true;
            WelcomeMessage = "Triggering server sync...";
            var resp = await _apiService.TriggerSyncAsync();
            if (resp.Success)
            {
                WelcomeMessage = "Server sync triggered successfully.";
            }
            else
            {
                WelcomeMessage = $"Sync failed: {resp.Error ?? "unknown"}";
            }

            // refresh dashboard after short delay
            await Task.Delay(1200);
            _ = LoadDashboardData();
        }
        catch (Exception ex)
        {
            WelcomeMessage = $"Sync error: {ex.Message}";
        }
        finally
        {
            IsLoading = false;
        }
    }

    private async Task LoadUserData()
    {
        var token = await _settingsService.GetTokenAsync();
        if (!string.IsNullOrEmpty(token))
        {
            var result = await _apiService.VerifyTokenAsync();
            if (result.Success && result.Data != null)
            {
                CurrentUser = result.Data;
                WelcomeMessage = $"Welcome, {CurrentUser.Username}!";
            }
        }
    }

    private async Task LoadDashboardData()
    {
        if (IsLoading) return;

        try
        {
            IsLoading = true;

            // Attempt to find current event from game config
            int? currentEventId = null;

            var configResp = await _apiService.GetGameConfigAsync();
            if (configResp.Success && configResp.Config != null && !string.IsNullOrEmpty(configResp.Config.CurrentEventCode))
            {
                var eventsResp = await _apiService.GetEventsAsync();
                if (eventsResp.Success && eventsResp.Events != null)
                {
                    // Try exact match first, then year+code combination, then suffix fallback
                    var yearCodeCombined = configResp.Config.Season > 0 ? $"{configResp.Config.Season}{configResp.Config.CurrentEventCode}" : null;
                    var ev = eventsResp.Events.FirstOrDefault(e => string.Equals(e.Code, configResp.Config.CurrentEventCode, System.StringComparison.OrdinalIgnoreCase))
                        ?? (yearCodeCombined != null ? eventsResp.Events.FirstOrDefault(e => string.Equals(e.Code, yearCodeCombined, System.StringComparison.OrdinalIgnoreCase)) : null)
                        ?? eventsResp.Events.FirstOrDefault(e => e.Code.EndsWith(configResp.Config.CurrentEventCode, System.StringComparison.OrdinalIgnoreCase));
                    if (ev != null)
                    {
                        currentEventId = ev.Id;
                        // set backing field and notify property changed
                        currentEventName = ev.DisplayName ?? ev.Code ?? "Current Event";
                        OnPropertyChanged("CurrentEventName");
                    }
                }
            }

            // If no current event found, try to pick a first event
            if (currentEventId == null)
            {
                var eventsResp = await _apiService.GetEventsAsync();
                if (eventsResp.Success && eventsResp.Events != null && eventsResp.Events.Any())
                {
                    var first = eventsResp.Events.First();
                    currentEventId = first.Id;
                    currentEventName = first.DisplayName ?? first.Code ?? "Event";
                    OnPropertyChanged("CurrentEventName");
                }
            }

            // Load team count (for current event if available)
            int countTeams = 0;
            var teamsResp = await _apiService.GetTeamsAsync(eventId: currentEventId, limit: 500);
            if (teamsResp.Success && teamsResp.Teams != null)
            {
                // Merge by team number could happen elsewhere; here just count unique numbers
                countTeams = teamsResp.Teams.Select(t => t.TeamNumber).Distinct().Count();
            }
            teamCount = countTeams;
            OnPropertyChanged("TeamCount");

            // Load match count for current event
            int countMatches = 0;
            if (currentEventId.HasValue)
            {
                var matchesResp = await _apiService.GetMatchesAsync(currentEventId.Value);
                if (matchesResp.Success && matchesResp.Matches != null)
                    countMatches = matchesResp.Matches.Count;
            }
            matchCount = countMatches;
            OnPropertyChanged("MatchCount");
        }
        catch (System.Exception ex)
        {
            System.Diagnostics.Debug.WriteLine($"[MainViewModel] LoadDashboardData error: {ex.Message}");
        }
        finally
        {
            IsLoading = false;
        }
    }

    [RelayCommand]
    private async Task LogoutAsync()
    {
        await _settingsService.ClearAuthDataAsync();

        // Update AppShell authentication state
        if (Shell.Current is AppShell appShell)
        {
            appShell.UpdateAuthenticationState(false);
        }

        await Shell.Current.GoToAsync("//LoginPage");
    }

    [RelayCommand]
    private async Task NavigateToTeamsAsync()
    {
        await Shell.Current.GoToAsync("TeamsPage");
    }

    [RelayCommand]
    private async Task NavigateToEventsAsync()
    {
        await Shell.Current.GoToAsync("EventsPage");
    }

    [RelayCommand]
    private async Task NavigateToScoutingAsync()
    {
        await Shell.Current.GoToAsync("ScoutingPage");
    }

    [RelayCommand]
    private async Task NavigateToGraphsAsync()
    {
        await Shell.Current.GoToAsync("GraphsPage");
    }
}
